# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

price_tier 0

app_review_information(
  first_name: "Anup V",
  last_name: "Menon",
  phone_number: "+914843223052",
  email_address: "anup@innovaturelabs.com",
  demo_user: "N/A",
  demo_password: "N/A",
  notes: ""
)

submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})
