# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do

    ensure_git_branch(
      branch: 'develop'
    )
    git_branch
    ensure_git_status_clean
    git_pull
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :release do
    produce(
      username: 'sysadmin@innovaturelabs.com',
      app_identifier: 'com.innovaturetech.donordiary',
      app_name: 'Donor Diary',
      language: 'English',
      app_version: '1.0',
      sku: 'DonorDiary1801'
    )
    deliver
  end

  lane :provision do
    cert
    sigh(app_identifier: "com.innovaturetech.donordiary",
         provisioning_name: "DonorDiaryAppInAppStore",
         username: "sysadmin@innovaturelabs.com",
         filename: "DonorDiaryAppInHouse.mobileprovision")
  end

  desc "Create ipa"
  lane :build do
    increment_build_number
    increment_version_number(
      bump_type: "minor" # Automatically increment minor version number
    )
    gym(clean: true,
        scheme: "DonorDiary")
    git_commit(path: ".", message: "Version incremeneted")
    push_to_git_remote
  end

  desc "Upload to App Store and submit for review"
  lane :upload do
    deliver(
      submit_for_review: true,
    )
  end

  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end
end
