# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  ############################## PRE ##############################

  before_all do
    ensure_git_status_clean
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    # crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Increment the version - use version:[major|minor] for versioning eg: fastlane incrementVersion version:major"
  lane :incrementVersion do
    if (options[:versionChange]== 'minor')

    else

    end
  end

  desc "Build App"
  lane :build do
    gradle(task: "clean")
    gradle(task: "assembleRelease")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    upload_to_play_store
  end
end
